# Generated by Django 5.2.8 on 2025-11-13 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0002_alter_simpleuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
