# Generated by Django 5.2.8 on 2025-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0003_alter_simpleuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='simpleuser',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
