# Generated by Django 5.2.8 on 2025-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0004_remove_simpleuser_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
