# Generated by Django 5.2.8 on 2025-11-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0005_alter_simpleuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleuser',
            options={'managed': False, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
