# Generated by Django 5.2.8 on 2025-11-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0006_alter_simpleuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
