# Generated by Django 5.2.6 on 2025-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0007_alter_simpleuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='correo',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='intentos_fallidos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='rol',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='simpleuser',
            table='Usuarios',
        ),
    ]
