# Generated by Django 5.2.6 on 2025-11-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0008_simpleuser_correo_alter_simpleuser_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleuser',
            options={'managed': False, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
