# Generated by Django 5.2.6 on 2025-11-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0009_alter_simpleuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='simpleuser',
            table='usuarios',
        ),
    ]
