# Generated by Django 5.2.6 on 2025-11-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigelin', '0010_alter_simpleuser_table'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='usuarios',
            table_comment=None,
        ),
    ]
